### ISSUE TITLE
Can't run normally

### ISSUE THREAD

**Issue by Yukayo** [weicy15/MGL#2]
Hi, thank you for your code, very impressive work. But based on the readme file, I can't run the code normally, for example, load_data.py lacks the data_load function, Test_dataset, and Test_dataset_one_plus_all class. If possible, could you please update the complete code

**Comment by weicy15** [comment]
I have uploaded the data_load function, Test_dataset, and Test_dataset_one_plus_all class in the new load_data.py. 
Please try it again
